---
- name: Ensure ~/.config/shell directory exists
  ansible.builtin.file:
    path: "{{ dev_user_home }}/.config/shell"
    state: directory
    mode: "0755"
  become: "{{ dev_user != ansible_user_id }}"
  become_user: "{{ dev_user }}"

- name: Place OS-specific shell snippet
  ansible.builtin.template:
    src: os.sh.j2
    dest: "{{ dev_user_home }}/.config/shell/os.sh"
    mode: "0644"
  become: "{{ dev_user != ansible_user_id }}"
  become_user: "{{ dev_user }}"

- name: Check if oh-my-zsh is installed
  ansible.builtin.stat:
    path: "{{ dev_user_home }}/.oh-my-zsh"
  register: omz_stat

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    executable: /bin/bash
  environment:
    HOME: "{{ dev_user_home }}"
  when: not omz_stat.stat.exists
  changed_when: true
  become: "{{ dev_user != ansible_user_id }}"
  become_user: "{{ dev_user }}"
