---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Install GNOME desktop environment
  ansible.builtin.package:
    name: "{{ gnome_packages }}"
    state: present
  become: true

- name: Enable and start GDM
  ansible.builtin.service:
    name: "{{ gnome_service }}"
    enabled: true
    state: started
  become: true
  failed_when: false

