---
all:
  children:
    workstations:
      hosts:
        localhost:
          ansible_connection: local
      # Add remote workstations here, e.g.:
      # my_laptop:
      #   ansible_host: 192.168.1.10
      #   ansible_user: balevision
    servers:
      hosts:
      # Add remote servers here, e.g.:
        workstation-test-debian-i3wm:
          ansible_host: 192.168.246.139
          ansible_user: vagrant
        workstation-test-ubuntu-i3wm:
          ansible_host: 192.168.246.142
          ansible_user: vagrant
        workstation-test-almalinux-i3wm:
          ansible_host: 192.168.246.143
          ansible_user: vagrant
