FROM almalinux:9

RUN dnf install -y ansible-core curl git sudo && \
    dnf clean all

RUN useradd -m -s /bin/bash user && \
    echo 'user ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER user
WORKDIR /home/user/workspace/workstation

COPY --chown=user:user . .

RUN ansible-galaxy collection install -r requirements.yml

RUN ansible-playbook playbooks/site.yml --syntax-check && \
    ansible-playbook playbooks/dotfiles.yml --syntax-check
