---
desktop_base_packages_apt:
  - xorg
  - xserver-xorg
  - dbus-x11
  - fonts-noto
  - fonts-noto-color-emoji

desktop_base_packages_dnf:
  - xorg-x11-server-Xwayland
  - xorg-x11-xinit
  - dbus-x11
  - google-noto-fonts-common
