---
- name: Install VM guest tools for desktop integration
  ansible.builtin.include_tasks: guest_tools.yml

- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_facts['os_family'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
      skip: true

- name: Install Xorg and display server base
  ansible.builtin.package:
    name: "{{ desktop_base_packages }}"
    state: present
  become: true

