---
- name: Include OS-specific variables
  ansible.builtin.include_vars: "{{ ansible_facts['os_family'] }}.yml"

- name: Install i3wm and supporting tools
  ansible.builtin.package:
    name: "{{ i3wm_packages }}"
    state: present
  become: true

- name: Enable and start LightDM
  ansible.builtin.service:
    name: lightdm
    enabled: true
    state: started
  become: true
  failed_when: false
