---
- name: Install i3wm and supporting tools (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ i3wm_packages_apt }}"
    state: present
    update_cache: true
  become: true
  when: ansible_os_family == "Debian"

- name: Install i3wm and supporting tools (RedHat/AlmaLinux)
  ansible.builtin.dnf:
    name: "{{ i3wm_packages_dnf }}"
    state: present
  become: true
  when: ansible_os_family == "RedHat"

- name: Set LightDM as display manager
  ansible.builtin.set_fact:
    desktop_display_manager: lightdm
