---
- name: Install i3wm and supporting tools (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ i3wm_packages_apt }}"
    state: present
    update_cache: true
  become: true
  when: ansible_facts['os_family'] == "Debian"

- name: Install i3wm and supporting tools (RedHat/AlmaLinux)
  ansible.builtin.dnf:
    name: "{{ i3wm_packages_dnf }}"
    state: present
  become: true
  when: ansible_facts['os_family'] == "RedHat"

- name: Enable and start LightDM
  ansible.builtin.service:
    name: lightdm
    enabled: true
    state: started
  become: true
