#!/usr/bin/env bash
# add-dev-host.sh — Scaffold and provision a workstation for a named developer.
#
# Automates the three manual steps in docs/custom-user.md:
#   1. Write inventory/host_vars/<hostname>.yml  (profile, dev_user, features)
#   2. Register the host under `workstations:` in inventory/hosts.yml
#   3. Run playbooks/site.yml limited to that host (with --run)
#
# Usage:
#   scripts/add-dev-host.sh -H <hostname> -d <dev_user> [options]
#
# Required:
#   -H, --host        Inventory hostname (e.g. devbox)
#   -d, --dev-user    Developer account to create (e.g. bach)
#
# Optional:
#   -i, --ip          ansible_host (IP/DNS). Omit for a local-only entry.
#   -u, --ssh-user    ansible_user — the SSH login Ansible connects as.
#                     Required when --ip is given.
#   -p, --profile     Environment profile (default: desktop-xfce).
#                     headless | desktop-gnome | desktop-xfce | desktop-i3wm
#   --xrdp            Enable features.xrdp (RDP access).
#   --fpga            Enable features.fpga (FPGA toolchain).
#       --run         Run the playbook after scaffolding.
#   -f, --force       Overwrite an existing host_vars file.
#   -h, --help        Show this help.
#
# Examples:
#   # Scaffold a remote XFCE box for user 'bach' with RDP, then provision:
#   scripts/add-dev-host.sh -H devbox -i 192.168.1.40 -u admin \
#       -d bach -p desktop-xfce --xrdp --run
#
#   # Scaffold only (review before running):
#   scripts/add-dev-host.sh -H devbox -i 192.168.1.40 -u admin -d bach

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
INVENTORY="${REPO_ROOT}/inventory/hosts.yml"
HOST_VARS_DIR="${REPO_ROOT}/inventory/host_vars"

# ── Defaults ────────────────────────────────────────────────────────────────
HOSTNAME=""
DEV_USER=""
ANSIBLE_HOST=""
SSH_USER=""
PROFILE="desktop-xfce"
ENABLE_XRDP="false"
ENABLE_FPGA="false"
RUN_PLAYBOOK="false"
FORCE="false"

usage() { sed -n '2,/^set -euo/p' "$0" | sed 's/^# \{0,1\}//; /^set -euo/d'; }

die() { echo "error: $*" >&2; exit 1; }

# ── Parse arguments ─────────────────────────────────────────────────────────
while [ $# -gt 0 ]; do
  case "$1" in
    -H|--host)     HOSTNAME="$2"; shift 2 ;;
    -d|--dev-user) DEV_USER="$2"; shift 2 ;;
    -i|--ip)       ANSIBLE_HOST="$2"; shift 2 ;;
    -u|--ssh-user) SSH_USER="$2"; shift 2 ;;
    -p|--profile)  PROFILE="$2"; shift 2 ;;
    --xrdp)        ENABLE_XRDP="true"; shift ;;
    --fpga)        ENABLE_FPGA="true"; shift ;;
    --run)         RUN_PLAYBOOK="true"; shift ;;
    -f|--force)    FORCE="true"; shift ;;
    -h|--help)     usage; exit 0 ;;
    *)             die "unknown option: $1 (try --help)" ;;
  esac
done

# ── Validate ────────────────────────────────────────────────────────────────
[ -n "$HOSTNAME" ] || die "missing -H/--host (try --help)"
[ -n "$DEV_USER" ] || die "missing -d/--dev-user (try --help)"

case "$PROFILE" in
  headless|desktop-gnome|desktop-xfce|desktop-i3wm) ;;
  *) die "invalid profile '$PROFILE' (headless|desktop-gnome|desktop-xfce|desktop-i3wm)" ;;
esac

# An IP requires an SSH user to log in with; without an IP we assume a local
# entry that the operator will wire up by hand or that resolves by name.
if [ -n "$ANSIBLE_HOST" ] && [ -z "$SSH_USER" ]; then
  die "--ip given without --ssh-user; Ansible needs an SSH login to connect"
fi

# ── 1. Write host_vars/<hostname>.yml ───────────────────────────────────────
HOST_VARS_FILE="${HOST_VARS_DIR}/${HOSTNAME}.yml"
mkdir -p "$HOST_VARS_DIR"

if [ -e "$HOST_VARS_FILE" ] && [ "$FORCE" != "true" ]; then
  die "$HOST_VARS_FILE already exists (use --force to overwrite)"
fi

cat > "$HOST_VARS_FILE" <<EOF
---
# ${HOSTNAME} — generated by scripts/add-dev-host.sh
# Provisions a dedicated developer account; see docs/custom-user.md.

profile: ${PROFILE}

dev_user: ${DEV_USER}

features:
  fpga: ${ENABLE_FPGA}
  xrdp: ${ENABLE_XRDP}
EOF
echo "==> wrote ${HOST_VARS_FILE#"$REPO_ROOT"/}"

# ── 2. Register host under `workstations:` in hosts.yml ─────────────────────
if grep -qE "^[[:space:]]+${HOSTNAME}:[[:space:]]*$" "$INVENTORY"; then
  echo "==> ${HOSTNAME} already present in inventory/hosts.yml — skipping"
else
  # Build the inventory block. 8-space indent for the host key, 10 for attrs,
  # matching the existing workstations entries.
  block="        ${HOSTNAME}:"
  if [ -n "$ANSIBLE_HOST" ]; then
    block="${block}"$'\n'"          ansible_host: ${ANSIBLE_HOST}"
    block="${block}"$'\n'"          ansible_user: ${SSH_USER}"
  fi

  # Insert immediately after the `hosts:` line that follows `workstations:`.
  # awk preserves all existing content and comments.
  tmp="$(mktemp)"
  awk -v block="$block" '
    /^[[:space:]]*workstations:[[:space:]]*$/ { in_ws = 1 }
    in_ws && /^[[:space:]]*hosts:[[:space:]]*$/ && !done {
      print
      print block
      done = 1
      next
    }
    { print }
  ' "$INVENTORY" > "$tmp"
  mv "$tmp" "$INVENTORY"
  echo "==> registered ${HOSTNAME} under workstations: in inventory/hosts.yml"
fi

# ── 3. Run the playbook (optional) ──────────────────────────────────────────
if [ "$RUN_PLAYBOOK" = "true" ]; then
  echo "==> running site.yml limited to ${HOSTNAME}"
  cd "$REPO_ROOT"
  # -K prompts for the SSH user's become password (needed to create the account
  # and write sudoers). The dev account itself gets passwordless sudo afterward.
  ansible-playbook playbooks/site.yml --inventory inventory/hosts.yml \
    --limit "$HOSTNAME" --ask-become-pass
else
  echo
  echo "Scaffolding complete. Review the files, then provision with:"
  echo "    ansible-playbook playbooks/site.yml -l ${HOSTNAME} -K"
fi
