#!/usr/bin/env python3
"""add_dev_host.py — Scaffold and provision a workstation for a named developer.

Cross-platform (Windows / Linux / macOS). Automates the three manual steps in
docs/custom-user.md:

  1. Write provisioning/inventory/host_vars/<hostname>.yml  (profile, dev_user, features)
  2. Register the host under ``workstations:`` in provisioning/inventory/hosts.yml
  3. Run provisioning/site.yml limited to that host (with --run)

Steps 1 and 2 are pure file edits and work everywhere, including a Windows host
with no Ansible installed. Step 3 shells out to ``ansible-playbook`` and so only
works where that is available (Linux, WSL, macOS).

Examples:
  # Scaffold a remote XFCE box for user 'bach' with RDP, then provision:
  python scripts/add_dev_host.py -H devbox -i 192.168.1.40 -u admin \\
      -d bach -p desktop-xfce --xrdp --run

  # Scaffold only (review before running):
  python scripts/add_dev_host.py -H devbox -i 192.168.1.40 -u admin -d bach
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INVENTORY = REPO_ROOT / "provisioning" / "inventory" / "hosts.yml"
HOST_VARS_DIR = REPO_ROOT / "provisioning" / "inventory" / "host_vars"

PROFILES = ("headless", "desktop-gnome", "desktop-xfce", "desktop-i3wm")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        prog="add_dev_host.py",
        description="Scaffold and provision a workstation for a named developer.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "examples:\n"
            "  python scripts/add_dev_host.py -H devbox -i 192.168.1.40 -u admin \\\n"
            "      -d bach -p desktop-xfce --xrdp --run\n"
            "  python scripts/add_dev_host.py -H devbox -i 192.168.1.40 -u admin -d bach\n"
        ),
    )
    p.add_argument("-H", "--host", required=True,
                   help="Inventory hostname (e.g. devbox)")
    p.add_argument("-d", "--dev-user", required=True,
                   help="Developer account to create (e.g. bach)")
    p.add_argument("-i", "--ip", default="",
                   help="ansible_host IP/DNS; omit for a local-only entry")
    p.add_argument("-u", "--ssh-user", default="",
                   help="ansible_user — SSH login Ansible connects as "
                        "(required with --ip)")
    p.add_argument("-p", "--profile", default="desktop-xfce", choices=PROFILES,
                   help="Environment profile (default: desktop-xfce)")
    p.add_argument("--xrdp", action="store_true",
                   help="Enable features.xrdp (RDP access)")
    p.add_argument("--fpga", action="store_true",
                   help="Enable features.fpga (FPGA toolchain)")
    p.add_argument("--run", action="store_true",
                   help="Run the playbook after scaffolding")
    p.add_argument("-f", "--force", action="store_true",
                   help="Overwrite an existing host_vars file")
    return p.parse_args(argv)


def die(msg: str) -> "NoReturn":  # type: ignore[name-defined]
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(1)


def rel(path: Path) -> str:
    """Repo-relative path with forward slashes, for tidy output on Windows."""
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return str(path)


def write_host_vars(args: argparse.Namespace) -> Path:
    HOST_VARS_DIR.mkdir(parents=True, exist_ok=True)
    host_vars_file = HOST_VARS_DIR / f"{args.host}.yml"

    if host_vars_file.exists() and not args.force:
        die(f"{rel(host_vars_file)} already exists (use --force to overwrite)")

    content = (
        "---\n"
        f"# {args.host} — generated by scripts/add_dev_host.py\n"
        "# Provisions a dedicated developer account; see docs/custom-user.md.\n"
        "\n"
        f"profile: {args.profile}\n"
        "\n"
        f"dev_user: {args.dev_user}\n"
        "\n"
        "features:\n"
        "  fpga:\n"
        f"    vivado: {str(args.fpga).lower()}\n"
        f"    quartus: {str(args.fpga).lower()}\n"
        f"    oss: {str(args.fpga).lower()}\n"
        f"  xrdp: {str(args.xrdp).lower()}\n"
    )
    # Newline="\n" pins LF even on Windows (matches .gitattributes for the repo).
    host_vars_file.write_text(content, encoding="utf-8", newline="\n")
    print(f"==> wrote {rel(host_vars_file)}")
    return host_vars_file


def register_in_inventory(args: argparse.Namespace) -> None:
    lines = INVENTORY.read_text(encoding="utf-8").splitlines()

    # Already present? (a key line like "        devbox:")
    host_key = re.compile(rf"^\s+{re.escape(args.host)}:\s*$")
    if any(host_key.match(line) for line in lines):
        print(f"==> {args.host} already present in inventory/hosts.yml — skipping")
        return

    # Build the block: 8-space indent for the host key, 10 for attributes,
    # matching the existing workstations entries.
    block = [f"        {args.host}:"]
    if args.ip:
        block.append(f"          ansible_host: {args.ip}")
        block.append(f"          ansible_user: {args.ssh_user}")

    # Insert immediately after the `hosts:` line that follows `workstations:`.
    ws_re = re.compile(r"^\s*workstations:\s*$")
    hosts_re = re.compile(r"^\s*hosts:\s*$")
    out: list[str] = []
    in_ws = False
    done = False
    for line in lines:
        out.append(line)
        if ws_re.match(line):
            in_ws = True
        elif in_ws and not done and hosts_re.match(line):
            out.extend(block)
            done = True

    if not done:
        die("could not find a `workstations:` -> `hosts:` block in "
            "inventory/hosts.yml to register the host under")

    INVENTORY.write_text("\n".join(out) + "\n", encoding="utf-8", newline="\n")
    print(f"==> registered {args.host} under workstations: in inventory/hosts.yml")


def run_playbook(args: argparse.Namespace) -> None:
    if shutil.which("ansible-playbook") is None:
        die("ansible-playbook not found on PATH — scaffolding is done, but "
            "--run needs Ansible (Linux/WSL/macOS). Re-run without --run on "
            "Windows, or provision from a Linux controller.")

    print(f"==> running site.yml limited to {args.host}")
    # -K prompts for the SSH user's become password (needed to create the
    # account and write sudoers). The dev account gets passwordless sudo after.
    cmd = [
        "ansible-playbook", "provisioning/site.yml",
        "--inventory", "provisioning/inventory/hosts.yml",
        "--limit", args.host,
        "--ask-become-pass",
    ]
    raise SystemExit(subprocess.run(cmd, cwd=REPO_ROOT).returncode)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)

    if args.ip and not args.ssh_user:
        die("--ip given without --ssh-user; Ansible needs an SSH login to connect")

    write_host_vars(args)
    register_in_inventory(args)

    if args.run:
        run_playbook(args)
    else:
        print()
        print("Scaffolding complete. Review the files, then provision with:")
        print(f"    ansible-playbook provisioning/site.yml -l {args.host} -K")


if __name__ == "__main__":
    main()
