---
- name: "Check neovim runtime"
  ansible.builtin.stat:
    path: "{{ dev_user_home }}/.local/nvim/bin/nvim"
  register: nvim_runtime_stat
  become: "{{ dev_user != ansible_facts['user_id'] }}"
  become_user: "{{ dev_user }}"

- name: "Check neovim version marker"
  ansible.builtin.stat:
    path: "{{ dev_tools_bin_dir }}/.neovim-{{ neovim_version }}"
  register: nvim_marker
  become: "{{ dev_user != ansible_facts['user_id'] }}"
  become_user: "{{ dev_user }}"

- name: Install neovim
  when: not nvim_marker.stat.exists or not nvim_runtime_stat.stat.exists
  block:
    - name: "Ensure neovim directory exists"
      ansible.builtin.file:
        path: "{{ dev_user_home }}/.local/nvim"
        state: directory

    - name: "Download and extract neovim"
      ansible.builtin.unarchive:
        src: "{{ neovim_url }}"
        dest: "{{ dev_user_home }}/.local/nvim"
        remote_src: yes
        extra_opts:
          - "--strip-components=1"

    - name: "Symlink nvim binary"
      ansible.builtin.file:
        src: "{{ dev_user_home }}/.local/nvim/bin/nvim"
        dest: "{{ dev_tools_bin_dir }}/nvim"
        state: link
        force: yes

    - name: "Write version marker for neovim"
      ansible.builtin.file:
        path: "{{ dev_tools_bin_dir }}/.neovim-{{ neovim_version }}"
        state: touch
        mode: "0644"

  become: "{{ dev_user != ansible_facts['user_id'] }}"
  become_user: "{{ dev_user }}"
