---
- name: Install fonts
  when: features.gui | default(false) | bool
  block:
    - name: Check if Nerd Fonts are installed
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.local/share/fonts/NerdFonts"
      register: nerd_fonts_stat
      when: features.fonts | default(true) | bool

    - name: Install FiraCode Nerd Font
      ansible.builtin.shell:
        cmd: |
          tmpdir=$(mktemp -d)
          git clone --depth 1 https://github.com/ryanoasis/nerd-fonts.git "$tmpdir"
          "$tmpdir/install.sh" FiraCode
          rm -rf "$tmpdir"
        executable: /bin/bash
      when: (features.fonts | default(true) | bool) and not nerd_fonts_stat.stat.exists
      changed_when: true
